In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [5]:
df=pd.read_csv("C:/Users/vasan/Downloads/Shopping_Customer_Dataset (1).csv")

In [7]:
df.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [8]:
df.tail()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [9]:
df.size

7000

In [10]:
df.shape

(1000, 7)

In [11]:
df.columns.tolist()

['Gender',
 'Product_Category',
 'Payment_Method',
 'Membership_Level',
 'City',
 'Customer_Rating',
 'Total_Items']

In [12]:
df.isnull().sum()

Gender              27
Product_Category     0
Payment_Method       0
Membership_Level     0
City                 0
Customer_Rating     28
Total_Items          0
dtype: int64

In [13]:
df.fillna({
"Gender":"Unknown",
"Product_Category":"Unknown",
"Payment_Method":"Unknown",
"Membership_Level":"Unknown",
"City":"Unknown"
},inplace=True)

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
...,...,...,...,...,...,...,...
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [14]:
df.drop_duplicates(inplace=True)

In [20]:
df["Date"]=pd.to_datetime(df["Product_Category"].astype(str),format="%Y",errors="coerce")
df.dtypes

Gender                        str
Product_Category              str
Payment_Method                str
Membership_Level              str
City                          str
Customer_Rating           float64
Total_Items                 int64
Date                datetime64[s]
dtype: object

In [23]:
df.loc[0:4,["Membership_Level","Customer_Rating"]]

  Membership_Level  Customer_Rating
0          Premium              4.6
1           Bronze              4.2
2           Silver              3.7
3           Silver              3.7
4           Silver              4.8

In [24]:
df.iloc[0:5,0:3]

   Gender Product_Category Payment_Method
0    Male           Beauty           Cash
1  Female   Home & Kitchen         PayPal
2  Female           Sports     Debit Card
3  Female      Electronics           Cash
4    Male           Sports         PayPal

In [26]:
df[df["Customer_Rating"]>1]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Date
0,Male,Beauty,Cash,Premium,Chicago,4.6,8,NaT
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2,NaT
2,Female,Sports,Debit Card,Silver,Miami,3.7,9,NaT
3,Female,Electronics,Cash,Silver,New York,3.7,5,NaT
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10,NaT
...,...,...,...,...,...,...,...,...
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7,NaT
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7,NaT
997,Male,Sports,Debit Card,Silver,Miami,2.3,8,NaT
998,Female,Beauty,PayPal,Gold,Houston,4.7,2,NaT
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9,NaT

In [28]:
df["Total_Items"]=df["City"]+df["Membership_Level"]
df.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Date
0,Male,Beauty,Cash,Premium,Chicago,4.6,ChicagoPremium,NaT
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,ChicagoBronze,NaT
2,Female,Sports,Debit Card,Silver,Miami,3.7,MiamiSilver,NaT
3,Female,Electronics,Cash,Silver,New York,3.7,New YorkSilver,NaT
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,Los AngelesSilver,NaT

In [30]:
df.groupby("Total_Items")["Customer_Rating"].mean()

Total_Items
ChicagoBronze         2.975758
ChicagoGold           2.730435
ChicagoPremium        2.805000
ChicagoSilver         2.876271
HoustonBronze         2.850725
HoustonGold           2.971429
HoustonPremium        2.600000
HoustonSilver         3.162687
Los AngelesBronze     3.100000
Los AngelesGold       3.065000
Los AngelesPremium    3.163158
Los AngelesSilver     2.974286
MiamiBronze           2.970130
MiamiGold             2.846512
MiamiPremium          2.866667
MiamiSilver           2.958730
New YorkBronze        2.834328
New YorkGold          3.272222
New YorkPremium       3.346667
New YorkSilver        3.067308
Name: Customer_Rating, dtype: float64

In [31]:
shape_before=df.shape

In [36]:
le=LabelEncoder()
df["Crop_Encoded"]=le.fit_transform(df["Customer_Rating"])
df.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Date,Crop_Encoded
0,Male,Beauty,Cash,Premium,Chicago,4.6,ChicagoPremium,NaT,36
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,ChicagoBronze,NaT,32
2,Female,Sports,Debit Card,Silver,Miami,3.7,MiamiSilver,NaT,27
3,Female,Electronics,Cash,Silver,New York,3.7,New YorkSilver,NaT,27
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,Los AngelesSilver,NaT,38

In [38]:
df=pd.get_dummies(df,columns=["Payment_Method"],dtype=int)
df.head()

,Gender,Product_Category,Membership_Level,City,Customer_Rating,Total_Items,Date,Crop_Encoded,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_PayPal
0,Male,Beauty,Premium,Chicago,4.6,ChicagoPremium,NaT,36,1,0,0,0
1,Female,Home & Kitchen,Bronze,Chicago,4.2,ChicagoBronze,NaT,32,0,0,0,1
2,Female,Sports,Silver,Miami,3.7,MiamiSilver,NaT,27,0,0,1,0
3,Female,Electronics,Silver,New York,3.7,New YorkSilver,NaT,27,1,0,0,0
4,Male,Sports,Silver,Los Angeles,4.8,Los AngelesSilver,NaT,38,0,0,0,1

In [41]:
oe=OrdinalEncoder()
df["State_Encoded"]=oe.fit_transform(df[["Product_Category"]])
df.head()

,Gender,Product_Category,Membership_Level,City,Customer_Rating,Total_Items,Date,Crop_Encoded,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_PayPal,State_Encoded
0,Male,Beauty,Premium,Chicago,4.6,ChicagoPremium,NaT,36,1,0,0,0,0.0
1,Female,Home & Kitchen,Bronze,Chicago,4.2,ChicagoBronze,NaT,32,0,0,0,1,3.0
2,Female,Sports,Silver,Miami,3.7,MiamiSilver,NaT,27,0,0,1,0,4.0
3,Female,Electronics,Silver,New York,3.7,New YorkSilver,NaT,27,1,0,0,0,2.0
4,Male,Sports,Silver,Los Angeles,4.8,Los AngelesSilver,NaT,38,0,0,0,1,4.0

In [42]:
df

,Gender,Product_Category,Membership_Level,City,Customer_Rating,Total_Items,Date,Crop_Encoded,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_PayPal,State_Encoded
0,Male,Beauty,Premium,Chicago,4.6,ChicagoPremium,NaT,36,1,0,0,0,0.0
1,Female,Home & Kitchen,Bronze,Chicago,4.2,ChicagoBronze,NaT,32,0,0,0,1,3.0
2,Female,Sports,Silver,Miami,3.7,MiamiSilver,NaT,27,0,0,1,0,4.0
3,Female,Electronics,Silver,New York,3.7,New YorkSilver,NaT,27,1,0,0,0,2.0
4,Male,Sports,Silver,Los Angeles,4.8,Los AngelesSilver,NaT,38,0,0,0,1,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Male,Clothing,Bronze,Houston,4.0,HoustonBronze,NaT,30,0,1,0,0,1.0
996,Female,Beauty,Silver,Houston,2.1,HoustonSilver,NaT,11,0,1,0,0,0.0
997,Male,Sports,Silver,Miami,2.3,MiamiSilver,NaT,13,0,0,1,0,4.0
998,Female,Beauty,Gold,Houston,4.7,HoustonGold,NaT,37,0,0,0,1,0.0
999,Male,Home & Kitchen,Silver,Miami,1.2,MiamiSilver,NaT,2,0,0,0,1,3.0