In [21]:
import numpy as np
import pandas as pd

In [22]:
a=np.array([10,20,30,40,50])

In [23]:
a.shape

(5,)

In [24]:
print(a)

[10 20 30 40 50]

In [25]:
series = pd.Series([10,20,30,40,50])
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [26]:
df = pd.DataFrame({"Name":["vasanth","selvi","kumar","naveen","praveen"],
                  "Age":[20,20,30,23,20],
                  "Mark":[85,80,90,40,90]})

In [27]:
print(df)

      Name  Age  Mark
0  vasanth   20    85
1    selvi   20    80
2    kumar   30    90
3   naveen   23    40
4  praveen   20    90

In [28]:
csv=pd.read_csv("C:/Users/vasan/Downloads/sales_data.csv")

In [29]:
print(csv)

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [30]:
csv.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [31]:
csv.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [32]:
csv.shape

(100, 6)

In [33]:
csv.columns

Index(['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice'], dtype='str')

In [34]:
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    100 non-null    int64
 1   Date       100 non-null    str
 2   Product    100 non-null    str
 3   Category   100 non-null    str
 4   Quantity   100 non-null    int64
 5   UnitPrice  100 non-null    int64
dtypes: int64(3), str(3)
memory usage: 4.8 KB